### ISSUE TITLE
Trade api sendOrder creates the orders but response of promise don't comes.

### ISSUE THREAD

**Issue by reinaldomendes** [blinktrade/BlinkTradeJS#25]
Hi,

Because I can't use the testnet platform I trying some tests in production. 

I guess when I'm create the order the promise should responds with OrdStatus: New, but nothing hapens.

My order enter in the order book but my code doesn't receive any response or errors it simple stucks.

![opera instantaneo_2017-10-27_023152_foxbit exchange](https://user-images.githubusercontent.com/725300/32088426-f6c709fa-bac1-11e7-92cc-21004c63a35c.png)

Follow the section of the code:

```js
const BlinkTradeWS = require("blinktrade").BlinkTradeWS;
  let prod = true
  let blinktrade = new BlinkTradeWS({ prod: prod });
//
// I'm abreviated the code to
//... connect ...
//.. login
//..

let options = { 
  msgType: 'D',
  side: '2', //sell
  price: (30000 * 1e8).toFixed(0), //R$ 30000
  amount: (0.0001 * 1e8).toFixed(0), // 0.0001
  brokerID: '4', //foxbit
  symbol: 'BTCBRL',
  ordType: '2', // limited
  clOrdID: '1' 
}

 blinktrade.sendOrder(options).then(function(order) {
           console.log(order); // this code doesn't executes
       }).catch(function(...args){
           console.log(args); //this code doesn't executes too
       });

`

**Comment by cesardeazevedo** [comment]
Thanks for report, i will take a look at it more closely tomorrow.

**Comment by cesardeazevedo** [comment]
I really sure that you are logging with an APIKey correct? so, here is some considerations.

1. If you are logging with an APIKey, you need to make sure that you checked notifications for execution report, otherwise you won't get any response when trying to sending orders.
2. You are passing strings on price and amount, which would show you an error if you checked execution report notifications.
```js
// Wrong
typeof (30000 * 1e8).toFixed(0) // string

// Correct
typeof parseInt((30000 * 1e8).toFixed(0)) // number
```

3. You shouldn't pass all those parameters, the client already abstract all of them for you, the JSON object shown on the [documentation](https://blinktrade.com/docs/?javascript#send-order) are just a reference of the full message that we send to the backend, it's also a reference for us and for others who are not using node.js and are developing in other language, so, we tried to make our [docs](https://blinktrade.com/docs) more generic, even though showing some examples with our node.js client, if you want to check a documentation more specifically to the client, you can find directly at the [README](https://github.com/blinktrade/BlinkTradeJS#sendorder-websocket-rest), i will try to make these things more clearly, but the only parameters that you need are, `side`, `price`, `amount`, `symbol`.

I didn't had any problems at getting responses, so, tell me if you got it.

**Comment by reinaldomendes** [comment]
@cesardeazevedo Thanks.

1 . It worked for me now, the problem was the notification permission in API keys.
2. In my code I'm don't passing strings, when I open this request I printed the option object in my console, So when I edited the object in this issue I don't added that correctly in example.
3. Thanks for show me the required parameters. In the API doc's (https://blinktrade.com/docs/#send-order) it is not clear.
