### ISSUE TITLE
Add Access-Control-Allow-Origin to response headers

### ISSUE THREAD

**Issue by viniciusbo** [blinktrade/BlinkTradeJS#32]
I'm building an web app that consumes BTC prices from exchanges from Brazil. Since I don't need everything inside `blinktrade` package and browsers need things lean and slim, I'd like to make a simple XHR cross domain request to fetch ticker prices. The problem is `Access-Control-Allow-Origin` response header is missing, throwing an error in the console: 

> Failed to load https://api.blinktrade.com/api/v1/BRL/ticker: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Do you have plans to support this header on public API responses?

**Comment by cesardeazevedo** [comment]
That's weird, the rest has always been open everywhere, i will ask my coworkers to understand what's going on.

**Comment by viniciusbo** [comment]
Anything new about this?

**Comment by pinhopro** [comment]
the public api is supposed to be consumed by apps running on the server side, and not on the browser.
We will not enable Access-Control-Allow-Origin

**Comment by viniciusbo** [comment]
That's confusing. `README.md` states:

> BlinkTradeJS WebSocket and REST Official JavasScript client for node.js and browser.

You don't plan to support browsers but package description says so...

**Comment by cesardeazevedo** [comment]
@viniciusbo Really sorry for that confusion, let me explain, everything worked before, but it worked with jsonp, but we recently dropped the support for jsonp, which i wasn't informed, and i also got surprised, and i completely forgot that was only by jsonp that we was be able to by pass our origin policy, without jsonp support, it completely breaks all the rest support for browser, resulting in false claims on our documentation indeed.

@pinhopro told me that we have been massively attacked on our rest endpoint, and he decided to drop the support for jsonp, and we also can't enable cors for all right now, since we have been target of a lots of phishing attacks.

We really apologize for that, the only thing that comes to my mind is to help you build a small express server to handle that for you and you can host on your own side (heroku, docker etc), yes, i know that's might not be convince for you, than just make a simple call, but let me know if you need any help with it.

but right know, we can't afford if your app gots hundreds of page views resulting in hundreds of http calls on our servers, we just can't handle that right now.

We're going to need some time until we have a better approach to support it, but the way that things were before, it wasn't really working for us, and i hope you understand, and also hope that this will change in the future.

I will update all our docs to avoid that confusion.

Kind Regards.

**Comment by viniciusbo** [comment]
@cesardeazevedo It's bad to hear about those attacks, but actually it's convincing enough, it's quite hard for us outside to know the big picture.

I really appreciate your effort to clarify that, thank you! This issue certainly will help others facing this same issue.

**Comment by pinhopro** [comment]
We just enable Access-Control-Allow-Origin

**Comment by cesardeazevedo** [comment]
Awesome news, thank you so much @pinhopro, i'm going to update the library ASAP.

**Comment by viniciusbo** [comment]
Great!
Em qui, 4 de jan de 2018 às 03:14, César D Azevedo <notifications@github.com>
escreveu:
