### ISSUE TITLE
withdraw from API key

### ISSUE THREAD

**Issue by LeoFCardoso** [blinktrade/BlinkTradeJS#40]
Maybe something is wrong with BTC withdrawals from websocket API.
My test was done with Python and testnet (https://testnet.blinktrade.com/).
API key / pass / secret was created with user "user" with password described in home page.
After successful logon in websocket with message "BE" / "BF", I send "B6" message:

`
{"MsgType": "U6", "WithdrawReqID": 314, "Method": "bitcoin", "Amount": 100086099, "Currency": "BTC", "Data": {"Wallet": "173D1zQQyzvCCCek9b1SpDvh7JikBEdtRJ", "Memo": "Testnet saque BTC"}}
`

API always answer with  "Not Authorized" message:

`
{"Request": {"Origin": "https://testnet.blinktrade.com", "GatewayID": "demo-1:ws_gateway_8443", "Currency": "BTC", "Amount": 100086099, "RemoteIP": "<sanitized_IPV6>", "WithdrawReqID": 314, "Data": {"Wallet": "173D1zQQyzvCCCek9b1SpDvh7JikBEdtRJ", "Memo": "Testnet saque BTC"}, "Method": "bitcoin"}, "MsgType": "ERROR", "Description": "Not authorized", "Detail": "U6"}
`

Thanks in advance!

**Comment by cesardeazevedo** [comment]
Hi, i just posted to this related issue at #39, so i will keep the discussion there, since you already subscribed, but indeed, bitcoin withdrawals from the API won't work for now, i've explained more at #39 

Other thing, `B6` message is used by brokers to process withdrawals, are you developing something on the broker side? or was a `U6` typo?

Let me know if you have any other question, or if your issue differs from there, fell free to reopen.

**Comment by LeoFCardoso** [comment]
Thank you. You're right, I'm sending "U6" and it was a typo.
I will wait for fix on #39.
