### ISSUE TITLE
Invalid username/password in prod

### ISSUE THREAD

**Issue by felipegtx** [blinktrade/BlinkTradeJS#48]
I'm getting the following error message even when using a fresh new API credential. Not sure what to do here. 

![image](https://user-images.githubusercontent.com/1022404/42101085-5e9776c2-7b98-11e8-85f9-7209df53807d.png)

The code is exactly [this one](https://github.com/felipegtx/algodinha/blob/master/algodinha.js#L1022-L1028).

**Comment by cesardeazevedo** [comment]
I think you forgot to pass the `brokerId: 4` [here](https://github.com/felipegtx/algodinha/blob/master/algodinha.js#L123)?

**Comment by felipegtx** [comment]
That seems to do the trick. :)

I'm assuming this being required is something new since it used to work without it.

**Comment by cesardeazevedo** [comment]
Nothing new actually, if you don't pass the brokerId, it will use the brokerId 5, which is the [blinktrade testnet](https://testnet.blinktrade.com/) for USD, now our beta versions will use brokerId 4 as default, but since you are using 0.0.15, it should fallback to 5 instead.

Also, there's no production environment for brokerId 5, so you can't use `prod: true` together with brokerId 5.

**Comment by felipegtx** [comment]
That's really weird. This thing used to work without it. 

Well, the thing is that it works now. Thanks!
